version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    restart: always
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    restart: always
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: nethmiumayapc
      MONGO_INITDB_ROOT_PASSWORD: abc
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  backend_node_modules:
  frontend_node_modules: