version: "3.8"

services:
  admin-backend:
    build: ./backend/restaurant-service/backend
    ports:
      - "5001:5001"
    restart: unless-stopped

  admin-frontend:
    build: ./backend/restaurant-service/admin
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - admin-backend

  main-frontend:
    build: ./frontend/web-app/Resturant managment
    ports:
      - "3001:3001"
    restart: unless-stopped
    depends_on:
      - admin-backend
